-- liquibase formatted sql

-- changeset janis:1699248938061-1
CREATE TABLE account
(
    account_number   VARCHAR(255) NOT NULL,
    account_currency VARCHAR(255),
    cust_id          BIGINT       NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (account_number)
);

-- changeset janis:1699248938061-2
CREATE TABLE balance
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_account_number VARCHAR(255),
    currency               VARCHAR(255),
    amount                 DECIMAL,
    CONSTRAINT pk_balance PRIMARY KEY (id)
);

-- changeset janis:1699248938061-3
CREATE TABLE customer
(
    cust_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    identity_number VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (cust_id)
);

-- changeset janis:1699248938061-4
CREATE TABLE rate
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    base      VARCHAR(3),
    output    VARCHAR(3),
    rate      DECIMAL,
    date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rate PRIMARY KEY (id)
);

-- changeset janis:1699248938061-5
CREATE TABLE request
(
    request_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    payment_type       SMALLINT                                NOT NULL,
    category           SMALLINT                                NOT NULL,
    account_src        VARCHAR(255)                            NOT NULL,
    account_dst        VARCHAR(255)                            NOT NULL,
    recipient_name     VARCHAR(255)                            NOT NULL,
    country_dst        SMALLINT,
    bank_dst           VARCHAR(255),
    payment_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    comission_coverage SMALLINT,
    swift              VARCHAR(255)                            NOT NULL,
    amount             DECIMAL                                 NOT NULL,
    currency           VARCHAR(3)                              NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    status             SMALLINT,
    date_time          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

-- changeset janis:1699248938061-6
CREATE TABLE transaction
(
    transaction_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number     VARCHAR(255),
    transaction_type   VARCHAR(255),
    transaction_status VARCHAR(255),
    currency           VARCHAR(3),
    amount             DECIMAL,
    request_id         BIGINT,
    date_time          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (transaction_id)
);

-- changeset janis:1699248938061-7
ALTER TABLE balance
    ADD CONSTRAINT uc_62cab7f0ff3416f1a80f78eec UNIQUE (account_account_number, currency);

-- changeset janis:1699248938061-8
ALTER TABLE customer
    ADD CONSTRAINT uc_customer_identitynumber UNIQUE (identity_number);

-- changeset janis:1699248938061-9
ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_CUST FOREIGN KEY (cust_id) REFERENCES customer (cust_id);

-- changeset janis:1699248938061-10
ALTER TABLE balance
    ADD CONSTRAINT FK_BALANCE_ON_ACCOUNT_ACCOUNT_NUMBER FOREIGN KEY (account_account_number) REFERENCES account (account_number);

-- changeset janis:1699248938061-11
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_ACCOUNT_NUMBER FOREIGN KEY (account_number) REFERENCES account (account_number);

-- changeset janis:1699248938061-12
ALTER TABLE transaction
    ADD CONSTRAINT FK_TRANSACTION_ON_REQUEST FOREIGN KEY (request_id) REFERENCES request (request_id);

